version: "3.8"

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 erp_core.wsgi:application"
    env_file:
      - .env.prod
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    networks:
      - erp_network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "80:80"
    networks:
      - erp_network
    depends_on:
      - web

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erp_network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - erp_network

volumes:
  postgres_data:
  redis_data:
  staticfiles:
  media:

networks:
  erp_network:
    driver: bridge
