version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn erp_core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - log_volume:/home/app/web/logs
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - erp_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    networks:
      - erp_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - erp_network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - erp_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  log_volume:

networks:
  erp_network:
    driver: bridge
