version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: erp_prod
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
