dev_up:
	@docker-compose -f docker-compose.dev.yml up --build

dev_down:
	@docker-compose -f docker-compose.dev.yml down -v

dev_shell:
	@docker-compose -f docker-compose.dev.yml exec web bash

dev_migrate:
	@docker-compose -f docker-compose.dev.yml exec web python manage.py migrate

dev_test:
	@docker-compose -f docker-compose.dev.yml exec web python manage.py test

dev_superuser:
	@docker-compose -f docker-compose.dev.yml exec web python manage.py createsuperuser

prod_up:
	@docker-compose -f docker-compose.prod.yml up --build

prod_down:
	@docker-compose -f docker-compose.prod.yml down -v

prod_shell:
	@docker-compose -f docker-compose.prod.yml exec web bash

prod_migrate:
		@docker-compose -f docker-compose.prod.yml exec web python manage.py migrate

prod_test:
	@docker-compose -f docker-compose.prod.yml exec web python manage.py test

prod_superuser:
	@docker-compose -f docker-compose.prod.yml exec web python manage.py createsuperuser

load_data:
	@# For production (after migrations):
	@docker-compose -f docker-compose.prod.yml exec web python manage.py load_inventory_data
	@docker-compose -f docker-compose.prod.yml exec web python manage.py load_raw_materials
	@docker-compose -f docker-compose.prod.yml exec web python manage.py load_standard_parts
	@docker-compose -f docker-compose.prod.yml exec web python manage.py load_semi_finished_products 
	@docker-compose -f docker-compose.prod.yml exec web python manage.py load_single_parts
	@docker-compose -f docker-compose.prod.yml exec web python manage.py load_montaged_products

load_data_dev:
	@# For development (after migrations):
	@docker-compose -f docker-compose.dev.yml exec web python manage.py load_inventory_data
	@docker-compose -f docker-compose.dev.yml exec web python manage.py load_raw_materials
	@docker-compose -f docker-compose.dev.yml exec web python manage.py load_standard_parts
	@docker-compose -f docker-compose.dev.yml exec web python manage.py load_semi_finished_products 
	@docker-compose -f docker-compose.dev.yml exec web python manage.py load_single_parts
	@docker-compose -f docker-compose.dev.yml exec web python manage.py load_montaged_products

## For manual backup:
./backup.sh

# To restore from a backup:
./restore.sh /path/to/full_backup_YYYYMMDD_HHMMSS.tar.gz