dev_up:
	@docker-compose -f docker-compose.dev.yml up --build

dev_down:
	@docker-compose -f docker-compose.dev.yml down -v

dev_shell:
	@docker-compose -f docker-compose.dev.yml exec web bash

dev_migrate:
	@docker-compose -f docker-compose.dev.yml exec web python manage.py migrate

dev_test:
	@docker-compose -f docker-compose.dev.yml exec web python manage.py test

dev_superuser:
	@docker-compose -f docker-compose.dev.yml exec web python manage.py createsuperuser

## For manual backup:
./backup.sh

# To restore from a backup:
./restore.sh /path/to/full_backup_YYYYMMDD_HHMMSS.tar.gz