# Generated by Django 5.1.5 on 2025-05-08 21:10

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Documents'), ('QUALITY', 'Quality Documents'), ('ORDER', 'Order Documents'), ('PRODUCT', 'Product Images'), ('MANUAL', 'Manuals'), ('REPORT', 'Reports'), ('OTHER', 'Other')], max_length=20)),
                ('max_size_mb', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'allowed_file_types',
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_category', models.CharField(choices=[('TECHNICAL', 'Technical Documents'), ('QUALITY', 'Quality Documents'), ('ORDER', 'Order Documents'), ('PRODUCT', 'Product Images'), ('MANUAL', 'Manuals'), ('REPORT', 'Reports'), ('OTHER', 'Other')], max_length=20)),
                ('content_type', models.CharField(choices=[('technical_drawing', 'Technical Drawing'), ('product_image', 'Product Image'), ('quality_document', 'Quality Document'), ('quality_image', 'Quality Image'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('work_order', 'Work Order'), ('maintenance_report', 'Maintenance Report'), ('user_manual', 'User Manual'), ('certificate', 'Certificate'), ('invoice', 'Invoice'), ('other', 'Other')], max_length=50)),
                ('object_id', models.CharField(help_text='ID of the related object', max_length=50)),
                ('version_number', models.PositiveIntegerField(help_text='Version number of this file')),
                ('file', models.FileField(storage='storages.backends.s3.S3Storage', upload_to=common.models.generate_file_path)),
                ('original_filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current version')),
                ('notes', models.TextField(blank=True, help_text='Notes about this version', null=True)),
                ('checksum', models.CharField(help_text='SHA256 checksum for integrity verification', max_length=64)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('is_image', models.BooleanField(default=False)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='file_versio_content_eb6af3_idx'), models.Index(fields=['content_type', 'object_id', 'is_current'], name='file_versio_content_f291fb_idx'), models.Index(fields=['file_category'], name='file_versio_file_ca_400cc7_idx'), models.Index(fields=['created_at'], name='file_versio_created_a05ee7_idx'), models.Index(fields=['checksum'], name='file_versio_checksu_5fb3d1_idx')],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
