# Generated by Django 5.1.5 on 2025-01-30 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HAMMADDE', 'Hammadde'), ('PROSES', 'Proses'), ('MAMUL', 'Mamül'), ('KARANTINA', 'Karantina'), ('HURDA', 'Hurda'), ('TAKIMHANE', 'Takımhane')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
            },
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('RETURN', 'Return'), ('TRANSFER', 'Category Transfer')], max_length=20),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='from_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='to_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='inventory_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory'),
        ),
    ]
