# Generated by Django 5.1.5 on 2025-05-08 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='manufacturing.workorder'),
        ),
        migrations.AddField(
            model_name='technicaldrawing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaldrawing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaldrawing',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaldrawing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_drawings', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='tool',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tool',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tool',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='inventory.tool'),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_usages', to='manufacturing.workorder'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure'),
        ),
        migrations.AlterUniqueTogether(
            name='productbom',
            unique_together={('parent_product', 'child_product', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'category', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', 'transaction_date'], name='stock_trans_product_a265c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='stock_trans_transac_b2b788_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference'], name='stock_trans_referen_6892c0_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['category'], name='stock_trans_categor_fad65b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['batch_number'], name='stock_trans_batch_n_1f283c_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaldrawing',
            index=models.Index(fields=['product', 'is_current'], name='technical_d_product_2fa6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaldrawing',
            index=models.Index(fields=['drawing_code'], name='technical_d_drawing_197715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicaldrawing',
            unique_together={('product', 'version')},
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tool_type'], name='tools_tool_ty_0f1122_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['status'], name='tools_status_c7bf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['next_maintenance_date'], name='tools_next_ma_2855d7_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusage',
            index=models.Index(fields=['tool'], name='tool_usages_tool_id_da3991_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusage',
            index=models.Index(fields=['work_order'], name='tool_usages_work_or_ab9f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusage',
            index=models.Index(fields=['issued_date'], name='tool_usages_issued__e126c5_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusage',
            index=models.Index(fields=['returned_date'], name='tool_usages_returne_590f40_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='products_product_15b636_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_product_af48aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['inventory_category'], name='products_invento_35a86d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['customer'], name='products_custome_eadc73_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
    ]
