# Generated by Django 5.1.5 on 2025-03-06 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MONTAGED', 'Montaged'), ('SEMI', 'Semi'), ('SINGLE', 'Single'), ('STANDARD_PART', 'Standard Part'), ('SPRING', 'Spring')], max_length=20),
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('unit_price_tl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holder_type', models.CharField(max_length=50)),
                ('pulley_type', models.CharField(max_length=50)),
                ('water_cooling', models.BooleanField(default=False)),
                ('distance_cooling', models.BooleanField(default=False)),
                ('tool_connection_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holder_type_enum', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('table_id', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holder',
                'verbose_name_plural': 'Holders',
                'indexes': [models.Index(fields=['product_code'], name='inventory_h_product_6f3a98_idx'), models.Index(fields=['row', 'column'], name='inventory_h_row_885176_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('unit_price_tl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_insert_code', models.CharField(max_length=100)),
                ('tool_material', models.CharField(max_length=100)),
                ('tool_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_angle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_radius', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_connection_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('table_id', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'indexes': [models.Index(fields=['product_code'], name='inventory_t_product_121355_idx'), models.Index(fields=['row', 'column'], name='inventory_t_row_860195_idx')],
            },
        ),
    ]
