# Generated by Django 5.1.5 on 2025-03-12 06:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_type_holder_tool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multicode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2147483648), django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.CreateModel(
            name='ControlGauge',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_type', models.CharField(max_length=50)),
                ('stock_description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Gauge',
                'verbose_name_plural': 'Control Gauges',
                'indexes': [models.Index(fields=['stock_name'], name='inventory_c_stock_n_79bc09_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_type', models.CharField(max_length=50)),
                ('stock_description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fixture',
                'verbose_name_plural': 'Fixtures',
                'indexes': [models.Index(fields=['stock_name'], name='inventory_f_stock_n_54bb2f_idx')],
            },
        ),
    ] 