# Generated by Django 4.2.8 on 2025-05-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('manufacturing', '0002_remove_processconfig_process_con_tool_id_f1eb6c_idx_and_more'), # Dependency on manufacturing might also be an issue for a clean delete.
        ('inventory', '0002_initial'), # Changed from 0003
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolUsage',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
