# Generated by Django 5.1.5 on 2025-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorytransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MONTAGED', 'Montaged'), ('SEMI', 'Semi'), ('SINGLE', 'Single'), ('STANDARD_PART', 'Standard Part')], max_length=20),
        ),
    ]
