# Generated by Django 5.1.5 on 2025-03-12 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_multicode_controlgauge_fixture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fixture',
            name='inventory_f_stock_n_54bb2f_idx',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='stock_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='stock_description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='stock_name',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='stock_type',
        ),
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif')], default='AKTIF', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['name'], name='inventory_f_name_a32f83_idx'),
        ),
    ]
