# Generated by Django 5.1.5 on 2025-03-12 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_fixture_inventory_f_stock_n_54bb2f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlgauge',
            old_name='stock_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='calibration_made_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='calibration_per_year',
            field=models.CharField(default='1 / Yıl', max_length=50),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='measuring_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='scrap_lost_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='status',
            field=models.CharField(choices=[('UYGUN', 'Uygun'), ('KULLANILMIYOR', 'Kullanılmıyor'), ('HURDA', 'Hurda'), ('KAYIP', 'Kayıp')], default='KULLANILMIYOR', max_length=20),
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='upcoming_calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='controlgauge',
            index=models.Index(fields=['status'], name='inventory_c_status_685a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='controlgauge',
            index=models.Index(fields=['calibration_date'], name='inventory_c_calibra_91450d_idx'),
        ),
    ]
