# Generated by Django 4.2.8 on 2025-05-21 18:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_dimensions_remove_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
