# Generated by Django 5.1.5 on 2025-02-11 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='diameter_mm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(choices=[('STEEL', 'Steel'), ('ALUMINUM', 'Aluminum')], default='STEEL', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='thickness',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='width',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
