# Generated by Django 5.1.5 on 2025-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_stock_description_controlgauge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlgauge',
            name='stock_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
