# Generated by Django 5.1.5 on 2025-04-16 20:27

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_controlgauge_stock_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTechnicalDrawing',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=20)),
                ('drawing_code', models.CharField(max_length=50)),
                ('drawing_file', models.TextField(blank=True, max_length=500, null=True)),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('revision_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Technical Drawing',
                'verbose_name_plural': 'historical Technical Drawings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveIndex(
            model_name='controlgauge',
            name='inventory_c_stock_n_79bc09_idx',
        ),
        migrations.RemoveIndex(
            model_name='controlgauge',
            name='inventory_c_calibra_91450d_idx',
        ),
        migrations.RemoveIndex(
            model_name='fixture',
            name='inventory_f_name_a32f83_idx',
        ),
        migrations.RemoveIndex(
            model_name='holder',
            name='inventory_h_product_6f3a98_idx',
        ),
        migrations.RemoveIndex(
            model_name='holder',
            name='inventory_h_row_885176_idx',
        ),
        migrations.RemoveIndex(
            model_name='tool',
            name='inventory_t_product_121355_idx',
        ),
        migrations.RemoveIndex(
            model_name='tool',
            name='inventory_t_row_860195_idx',
        ),
        migrations.RemoveField(
            model_name='holder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='controlgauge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='holder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='controlgauge',
            name='status',
            field=models.CharField(choices=[('UYGUN', 'Uygun'), ('KULLANILMIYOR', 'Kullanılmıyor'), ('HURDA', 'Hurda'), ('KAYIP', 'Kayıp'), ('BAKIMDA', 'Bakımda'), ('KALIBRASYONDA', 'Kalibrasyonda')], default='KULLANILMIYOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='controlgauge',
            name='stock_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='holder',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('DAMAGED', 'Damaged'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='holder',
            name='stock_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('DAMAGED', 'Damaged'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='stock_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='controlgauge',
            index=models.Index(fields=['upcoming_calibration_date'], name='inventory_c_upcomin_bf5c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status'], name='inventory_f_status_2e6b74_idx'),
        ),
        migrations.AddIndex(
            model_name='holder',
            index=models.Index(fields=['holder_type'], name='inventory_h_holder__ad37b3_idx'),
        ),
        migrations.AddIndex(
            model_name='holder',
            index=models.Index(fields=['status'], name='inventory_h_status_7f2866_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['tool_type'], name='inventory_t_tool_ty_9d6388_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['status'], name='inventory_t_status_d42220_idx'),
        ),
        migrations.AddField(
            model_name='historicaltechnicaldrawing',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltechnicaldrawing',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltechnicaldrawing',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltechnicaldrawing',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltechnicaldrawing',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product'),
        ),
    ]
