# Generated by Django 5.1.5 on 2025-02-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rawmaterial_diameter_mm_rawmaterial_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicaldrawing',
            name='drawing_url',
        ),
        migrations.AddField(
            model_name='technicaldrawing',
            name='drawing_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='technical_drawings/%Y/%m/%d/'),
        ),
    ]
