# Generated by Django 4.2.8 on 2025-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_holder_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['stock_code']},
        ),
        migrations.AlterModelOptions(
            name='productbom',
            options={'ordering': ['operation_sequence', 'child_product__stock_code']},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['stock_code'], 'verbose_name': 'Raw Material', 'verbose_name_plural': 'Raw Materials'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_product_15b636_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawmaterial',
            name='raw_materia_materia_373826_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_code',
            new_name='stock_code',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='material_code',
            new_name='stock_code',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_code'], name='products_stock_c_ca971e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterial',
            index=models.Index(fields=['stock_code'], name='raw_materia_stock_c_acc46e_idx'),
        ),
    ]
