# Generated by Django 5.1.5 on 2025-02-27 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_technicaldrawing_drawing_url_and_more'),
        ('manufacturing', '0028_bomprocessconfig_raw_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('bom_process_configs', models.ManyToManyField(help_text='The BOM process configurations this product is associated with', related_name='process_products', to='manufacturing.bomprocessconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('parent_product', models.ForeignKey(help_text='The parent product (SEMI or SINGLE) this process product belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='process_products', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Process Product',
                'verbose_name_plural': 'Process Products',
                'ordering': ['product_code'],
                'indexes': [models.Index(fields=['parent_product'], name='inventory_p_parent__f61c44_idx'), models.Index(fields=['product_code'], name='inventory_p_product_3139f3_idx')],
            },
        ),
    ]
