# Generated by Django 5.1.5 on 2025-02-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_processproduct_bom_process_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processproduct',
            name='bom_process_configs',
        ),
    ]
