# Generated by Django 5.1.5 on 2025-03-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_processproduct_bom_process_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multicode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
