# Generated by Django 5.1.5 on 2025-03-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_multicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
