# Generated by Django 5.1.5 on 2025-01-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('view_customer_dashboard', 'Can view customer dashboard')],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_code', models.CharField(max_length=50, unique=True)),
                ('process_name', models.CharField(max_length=100)),
                ('standard_time_minutes', models.IntegerField()),
                ('machine_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BOMProcessConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_type', models.CharField(max_length=50)),
                ('estimated_duration_minutes', models.IntegerField()),
                ('tooling_requirements', models.JSONField()),
                ('quality_checks', models.JSONField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.manufacturingprocess')),
            ],
            options={
                'verbose_name': 'BOM Process Configuration',
                'verbose_name_plural': 'BOM Process Configurations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('MONTAGED', 'Montaged Product'), ('SEMI', 'Semi-Finished'), ('SINGLE', 'Single Part')], max_length=20)),
                ('current_stock', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('SEMI_PRODUCT', 'Semi-Product'), ('MANUFACTURING_PROCESS', 'Manufacturing Process'), ('RAW_MATERIAL', 'Raw Material')], max_length=25)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sequence_order', models.IntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.bom')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial')),
                ('process_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.bomprocessconfig')),
                ('semi_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.product')),
            ],
            options={
                'verbose_name': 'BOM Component',
                'verbose_name_plural': 'BOM Components',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.product'),
        ),
        migrations.CreateModel(
            name='TechnicalDrawing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('drawing_code', models.CharField(max_length=50)),
                ('drawing_url', models.URLField(max_length=500)),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision_notes', models.CharField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.product')),
            ],
            options={
                'verbose_name': 'Technical Drawing',
                'verbose_name_plural': 'Technical Drawings',
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['product'], name='manufacturi_product_60b29a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product', 'version')},
        ),
        migrations.AddIndex(
            model_name='technicaldrawing',
            index=models.Index(fields=['product', 'is_current'], name='manufacturi_product_917bf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicaldrawing',
            unique_together={('product', 'version')},
        ),
    ]
