# Generated by Django 5.1.5 on 2025-03-05 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='sales_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='subworkorder',
            name='parent_work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='manufacturing.workorder'),
        ),
        migrations.AddField(
            model_name='workorderoutput',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderoutput',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderoutput',
            name='sub_work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='manufacturing.subworkorder'),
        ),
        migrations.AddField(
            model_name='workorderoutput',
            name='target_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='manufacturing.workorder'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['product'], name='manufacturi_product_60b29a_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['is_active'], name='manufacturi_is_acti_40200b_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['is_approved'], name='manufacturi_is_appr_93510b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product', 'version')},
        ),
        migrations.AddIndex(
            model_name='bomcomponent',
            index=models.Index(fields=['bom'], name='manufacturi_bom_id_dc85e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bomcomponent',
            index=models.Index(fields=['sequence_order'], name='manufacturi_sequenc_8032c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomcomponent',
            unique_together={('bom', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='manufacturi_status_398ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['machine_type'], name='manufacturi_machine_43117d_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingprocess',
            index=models.Index(fields=['process_code'], name='manufacturi_process_75a233_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingprocess',
            index=models.Index(fields=['machine_type'], name='manufacturi_machine_eb608f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowprocess',
            index=models.Index(fields=['product'], name='manufacturi_product_40e01d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowprocess',
            index=models.Index(fields=['process_number'], name='manufacturi_process_8f333b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowprocess',
            index=models.Index(fields=['stock_code'], name='manufacturi_stock_c_5f4b82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowprocess',
            unique_together={('product', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['sub_work_order'], name='manufacturi_sub_wor_5cbfb1_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['workflow_process'], name='manufacturi_workflo_51cefd_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['machine'], name='manufacturi_machine_6ab787_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['status'], name='manufacturi_status_866069_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['start_time'], name='manufacturi_start_t_c62f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['end_time'], name='manufacturi_end_tim_b021f0_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='manufacturi_status_305de3_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='manufacturi_priorit_cd3830_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['planned_start'], name='manufacturi_planned_061555_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['planned_end'], name='manufacturi_planned_2c495e_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['status'], name='manufacturi_status_389beb_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['parent_work_order'], name='manufacturi_parent__a7471b_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['planned_start'], name='manufacturi_planned_3030bc_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['planned_end'], name='manufacturi_planned_b11565_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['status'], name='manufacturi_status_0153b9_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['sub_work_order'], name='manufacturi_sub_wor_9b110c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['target_category'], name='manufacturi_target__315ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['inspection_required'], name='manufacturi_inspect_72c913_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['production_date'], name='manufacturi_product_8fa06e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderstatuschange',
            index=models.Index(fields=['work_order'], name='manufacturi_work_or_5b924c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderstatuschange',
            index=models.Index(fields=['changed_at'], name='manufacturi_changed_b920fc_idx'),
        ),
    ]
