# Generated by Django 5.1.5 on 2025-03-05 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Reference to the product used in this component', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Reference to the material used in this component (deprecated)', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial'),
        ),
    ]
