# Generated by Django 4.2.8 on 2025-05-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_code_fields'),
        ('manufacturing', '0002_remove_processconfig_process_con_tool_id_f1eb6c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processconfig',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tool'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['tool'], name='process_con_tool_id_f1eb6c_idx'),
        ),
    ]
