# Generated by Django 4.2.8 on 2025-05-31 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0003_processconfig_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_type', models.CharField(choices=[('CNC_MILLING', 'CNC Milling'), ('CNC_LATHE', 'CNC Lathe'), ('DRILLING', 'Drilling'), ('GRINDING', 'Grinding'), ('WELDING', 'Welding'), ('ASSEMBLY', 'Assembly'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('axis_count', models.CharField(blank=True, choices=[('AXIS_2', '2-Axis'), ('AXIS_3', '3-Axis'), ('AXIS_4', '4-Axis'), ('AXIS_5', '5-Axis'), ('AXIS_6', '6-Axis'), ('MULTI', 'Multi-Axis')], max_length=20, null=True)),
                ('internal_cooling', models.DecimalField(blank=True, decimal_places=2, help_text='Internal cooling pressure in bars', max_digits=10, null=True)),
                ('motor_power_kva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('holder_type', models.CharField(blank=True, max_length=50, null=True)),
                ('spindle_motor_power_10_percent_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spindle_motor_power_30_percent_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_hp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spindle_speed_rpm', models.IntegerField(blank=True, null=True)),
                ('tool_count', models.IntegerField(blank=True, null=True)),
                ('nc_control_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturing_year', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('machine_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_part_size', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Under Maintenance'), ('BROKEN', 'Broken'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('maintenance_interval', models.IntegerField(default=90, help_text='Days between required maintenance')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='manufacturing.workcenter')),
            ],
            options={
                'db_table': 'machines',
                'ordering': ['machine_code'],
                'indexes': [models.Index(fields=['machine_code'], name='machines_machine_3b42f6_idx'), models.Index(fields=['status'], name='machines_status_83686b_idx'), models.Index(fields=['machine_type'], name='machines_machine_86bbdf_idx'), models.Index(fields=['work_center'], name='machines_work_ce_b1687f_idx'), models.Index(fields=['next_maintenance_date'], name='machines_next_ma_fc8f01_idx')],
            },
        ),
    ]
