# Generated by Django 5.1.5 on 2025-01-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_alter_workorder_sales_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomcomponent',
            name='component_type',
            field=models.CharField(choices=[('SEMI_PRODUCT', 'Semi Product'), ('MONTAGED_PRODUCT', 'Montaged Product'), ('RAW_MATERIAL', 'Raw Material')], max_length=30),
        ),
    ]
