# Generated by Django 5.1.5 on 2025-03-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0004_data_migration_material_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomcomponent',
            name='material',
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='product',
            field=models.ForeignKey(help_text='Reference to the product used in this component', on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
