# Generated by Django 5.1.5 on 2025-01-31 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_product_type'),
        ('manufacturing', '0004_alter_bomcomponent_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='standard_part',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'STANDARD_PART'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standard_components', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='component_type',
            field=models.CharField(choices=[('SEMI_PRODUCT', 'Semi Product'), ('MONTAGED_PRODUCT', 'Montaged Product'), ('RAW_MATERIAL', 'Raw Material'), ('STANDARD_PART', 'Standard Part')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_components', to='inventory.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='semi_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semi_components', to='inventory.product'),
        ),
    ]
