# Generated by Django 4.2.8 on 2025-06-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_calibrationrecord_calibration_control_bd1694_idx_and_more'),
        ('manufacturing', '0004_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='production_line',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='machines_work_ce_b1687f_idx',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='work_center',
        ),
        migrations.RemoveField(
            model_name='machinedowntime',
            name='work_center',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='work_center',
        ),
        migrations.RemoveField(
            model_name='workorderoperation',
            name='work_center',
        ),
        migrations.AddField(
            model_name='machine', 
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machinedowntime',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='manufacturing.machine'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='primary_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_work_orders', to='manufacturing.machine'),
        ),
        migrations.AddField(
            model_name='workorderoperation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='manufacturing.machine'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['machine'], name='machine_dow_machine_48a2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['start_time'], name='machine_dow_start_t_d3d8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['category'], name='machine_dow_categor_84ef46_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['primary_machine'], name='work_orders_primary_fe6c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['machine'], name='work_order__machine_4918cd_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['status'], name='work_order__status_1cdb69_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['planned_start_date'], name='work_order__planned_e310fd_idx'),
        ),
        migrations.DeleteModel(
            name='ProductionLine',
        ),
        migrations.DeleteModel(
            name='WorkCenter',
        ),
    ]
