# Generated by Django 4.2.8 on 2025-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_remove_productionline_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fixture',
            name='fixture_name_88bb29_idx',
        ),
        migrations.RemoveIndex(
            model_name='processconfig',
            name='process_con_workflo_7c7bfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='processconfig',
            name='process_con_workflo_e3889d_idx',
        ),
        migrations.RemoveIndex(
            model_name='processconfig',
            name='process_con_version_0056b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='productworkflow',
            name='product_wor_product_eb0959_idx',
        ),
        migrations.AddIndex(
            model_name='controlgauge',
            index=models.Index(fields=['code'], name='control_gau_code_c55672_idx'),
        ),
        migrations.AddIndex(
            model_name='controlgauge',
            index=models.Index(fields=['manufacturer'], name='control_gau_manufac_e9694a_idx'),
        ),
        migrations.AddIndex(
            model_name='controlgauge',
            index=models.Index(fields=['status', 'upcoming_calibration_date'], name='control_gau_status_ccf3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='controlgauge',
            index=models.Index(fields=['manufacturer', 'status'], name='control_gau_manufac_c049b3_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['code'], name='fixture_code_ab9272_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['next_check_date'], name='fixture_next_ch_e5f271_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['fixture_type'], name='fixture_fixture_4e9e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['last_checked'], name='fixture_last_ch_def1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status', 'fixture_type'], name='fixture_status_8932fa_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status', 'next_check_date'], name='fixture_status_307c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['is_active'], name='machines_is_acti_d870cd_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['last_maintenance_date'], name='machines_last_ma_69c534_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['serial_number'], name='machines_serial__83a8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status', 'machine_type'], name='machines_status_088dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['machine_type', 'is_active'], name='machines_machine_1394fe_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['end_time'], name='machine_dow_end_tim_ff32c1_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['reported_by'], name='machine_dow_reporte_c99d40_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['machine', 'category'], name='machine_dow_machine_33dd7f_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['machine', 'start_time'], name='machine_dow_machine_032e46_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntime',
            index=models.Index(fields=['category', 'start_time'], name='machine_dow_categor_347d87_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingprocess',
            index=models.Index(fields=['name'], name='manufacturi_name_26f447_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingprocess',
            index=models.Index(fields=['machine_type', 'name'], name='manufacturi_machine_288e37_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['work_order'], name='material_al_work_or_ee8a04_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['material'], name='material_al_materia_2cc8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['is_allocated'], name='material_al_is_allo_7bdb87_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['allocation_date'], name='material_al_allocat_89bd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['work_order', 'is_allocated'], name='material_al_work_or_68fdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['material', 'is_allocated'], name='material_al_materia_7cc66b_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['workflow'], name='process_con_workflo_513469_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['process'], name='process_con_process_0d1c42_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['machine_type'], name='process_con_machine_a0bd11_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['axis_count'], name='process_con_axis_co_6ba5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['workflow', 'status'], name='process_con_workflo_1d286b_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['process', 'status'], name='process_con_process_58edc6_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['machine_type', 'axis_count'], name='process_con_machine_339a41_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['work_order'], name='production__work_or_45b20e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['operation'], name='production__operati_303a78_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['operator'], name='production__operato_ceee40_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['output_date'], name='production__output__d48cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['batch_number'], name='production__batch_n_aad8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['work_order', 'output_date'], name='production__work_or_4659c4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionoutput',
            index=models.Index(fields=['operator', 'output_date'], name='production__operato_f94809_idx'),
        ),
        migrations.AddIndex(
            model_name='productworkflow',
            index=models.Index(fields=['product'], name='product_wor_product_5e1ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='productworkflow',
            index=models.Index(fields=['status'], name='product_wor_status_ef0768_idx'),
        ),
        migrations.AddIndex(
            model_name='productworkflow',
            index=models.Index(fields=['approved_by'], name='product_wor_approve_2af7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productworkflow',
            index=models.Index(fields=['approval_date'], name='product_wor_approva_8e9f96_idx'),
        ),
        migrations.AddIndex(
            model_name='productworkflow',
            index=models.Index(fields=['status', 'effective_date'], name='product_wor_status_09fc56_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['work_order_number'], name='sub_work_or_work_or_d54c21_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['actual_start'], name='sub_work_or_actual__2a5cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['actual_end'], name='sub_work_or_actual__0f0111_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['parent_work_order', 'status'], name='sub_work_or_parent__f3f676_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['assigned_to', 'status'], name='sub_work_or_assigne_4e2b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['target_category', 'status'], name='sub_work_or_target__c9ea28_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='work_orders_priorit_9f375c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['product'], name='work_orders_product_2c0bae_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['planned_end_date'], name='work_orders_planned_e0a790_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['actual_start_date'], name='work_orders_actual__ae28b7_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['actual_end_date'], name='work_orders_actual__f2af13_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['sales_order'], name='work_orders_sales_o_6bcf33_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'priority'], name='work_orders_status_d07f78_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'planned_start_date'], name='work_orders_status_3f48e0_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['product', 'status'], name='work_orders_product_8bdb19_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['primary_machine', 'status'], name='work_orders_primary_243b82_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['work_order'], name='work_order__work_or_a873b9_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['assigned_to'], name='work_order__assigne_d075fe_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['planned_end_date'], name='work_order__planned_20ef94_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['actual_start_date'], name='work_order__actual__a196e8_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['actual_end_date'], name='work_order__actual__5ec0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['work_order', 'status'], name='work_order__work_or_e893e9_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['machine', 'status'], name='work_order__machine_bc99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoperation',
            index=models.Index(fields=['assigned_to', 'status'], name='work_order__assigne_8cf84f_idx'),
        ),
    ]
