# Generated by Django 5.1.5 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_remove_bomcomponent_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomcomponent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
