# Generated by Django 5.1.5 on 2025-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_bomcomponent_standard_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenance_interval',
            field=models.IntegerField(default=90, help_text='Days between required maintenance'),
        ),
        migrations.AddField(
            model_name='machine',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
