# Generated by Django 5.1.5 on 2025-03-11 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_type_holder_tool'),
        ('manufacturing', '0006_alter_bomcomponent_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowprocess',
            name='axis_count',
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='estimated_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='quality_checks',
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='tooling_requirements',
        ),
        migrations.CreateModel(
            name='ProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('axis_count', models.CharField(blank=True, choices=[('9EKSEN', '9 Eksen'), ('8.5EKSEN', '8.5 Eksen'), ('5EKSEN', '5 Eksen'), ('4EKSEN', '4 Eksen'), ('3EKSEN', '3 Eksen'), ('2EKSEN', '2 Eksen'), ('1EKSEN', '1 Eksen')], help_text='Required machine axis count for this process', max_length=20, null=True)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, help_text='Estimated time to complete this process in minutes', null=True)),
                ('tooling_requirements', models.TextField(blank=True, help_text='Tools and equipment required for this process', null=True)),
                ('quality_checks', models.TextField(blank=True, help_text='Quality control procedures for this process', null=True)),
                ('machine_type', models.CharField(blank=True, choices=[('İşleme Merkezi', 'İşleme Merkezi'), ('CNC Torna Merkezi', 'CNC Torna Merkezi'), ('CNC Kayar Otomat', 'CNC Kayar Otomat'), ('Yok', 'Yok')], help_text='Type of machine required for this process', max_length=50, null=True)),
                ('setup_time_minutes', models.IntegerField(blank=True, help_text='Time required to set up the machine in minutes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions for this process', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(blank=True, help_text='Raw material required for this process', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial')),
                ('workflow_process', models.ForeignKey(help_text='The workflow process this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='process_configs', to='manufacturing.workflowprocess')),
            ],
            options={
                'verbose_name': 'Process Configuration',
                'verbose_name_plural': 'Process Configurations',
            },
        ),
        migrations.AddField(
            model_name='subworkorderprocess',
            name='process_config',
            field=models.ForeignKey(blank=True, help_text='Specific process configuration to use', null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.processconfig'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['process_config'], name='manufacturi_process_a4e5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['workflow_process'], name='manufacturi_workflo_15238b_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['machine_type'], name='manufacturi_machine_462cba_idx'),
        ),
    ]
