# Generated by Django 5.1.5 on 2025-02-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_technicaldrawing_drawing_url_and_more'),
        ('manufacturing', '0007_machine_maintenance_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomcomponent',
            options={},
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='semi_product',
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.manufacturingprocess'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('product_type__in', ['SEMI', 'MONTAGED'])), null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='component_type',
            field=models.CharField(choices=[('PROCESS', 'Manufacturing Process'), ('SEMI', 'Semi-Finished Product'), ('MONTAGED', 'Montaged Product'), ('STANDARD', 'Standard Part'), ('RAW', 'Raw Material')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='axis_count',
            field=models.CharField(blank=True, choices=[('9EKSEN', '9 Eksen'), ('8.5EKSEN', '8.5 Eksen'), ('5EKSEN', '5 Eksen'), ('4EKSEN', '4 Eksen'), ('3EKSEN', '3 Eksen'), ('2EKSEN', '2 Eksen'), ('1EKSEN', '1 Eksen')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('İşleme Merkezi', 'İşleme Merkezi'), ('CNC Torna Merkezi', 'CNC Torna Merkezi'), ('CNC Kayar Otomat', 'CNC Kayar Otomat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufacturing_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingprocess',
            name='machine_type',
            field=models.CharField(choices=[('İşleme Merkezi', 'İşleme Merkezi'), ('CNC Torna Merkezi', 'CNC Torna Merkezi'), ('CNC Kayar Otomat', 'CNC Kayar Otomat')], max_length=50),
        ),
    ]
