# Generated by Django 4.2.8 on 2025-06-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_add_audit_logging'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE machines DROP COLUMN IF EXISTS capacity_per_hour;",
            reverse_sql="ALTER TABLE machines ADD COLUMN capacity_per_hour DECIMAL(10,2) NOT NULL DEFAULT 0;"
        ),
        migrations.RunSQL(
            "ALTER TABLE machines DROP COLUMN IF EXISTS setup_time_minutes;",
            reverse_sql="ALTER TABLE machines ADD COLUMN setup_time_minutes INTEGER NOT NULL DEFAULT 0;"
        ),
    ]
