# Generated by Django 4.2.8 on 2025-06-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_remove_orphaned_machine_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processconfig',
            name='parameters',
        ),
        migrations.AddField(
            model_name='processconfig',
            name='connecting_count',
            field=models.IntegerField(default=0, help_text='Connecting and count time in minutes'),
        ),
        migrations.AlterField(
            model_name='processconfig',
            name='sequence_order',
            field=models.PositiveIntegerField(),
        ),
    ]
