# Generated by Django 5.1.5 on 2025-03-12 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_multicode_controlgauge_fixture'),
        ('manufacturing', '0008_remove_workflowprocess_manufacturi_process_8f333b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processconfig',
            options={'ordering': ['workflow_process', 'machine_type'], 'verbose_name': 'Process Configuration', 'verbose_name_plural': 'Process Configurations'},
        ),
        migrations.RenameField(
            model_name='processconfig',
            old_name='setup_time_minutes',
            new_name='setup_time',
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='axis_count',
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='estimated_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='quality_checks',
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='tooling_requirements',
        ),
        migrations.AddField(
            model_name='processconfig',
            name='control_gauge',
            field=models.ForeignKey(blank=True, help_text='Control gauge required for quality checks in this process', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.controlgauge'),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='fixture',
            field=models.ForeignKey(blank=True, help_text='Fixture required for this process', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.fixture'),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='machine_time',
            field=models.IntegerField(blank=True, help_text='Time required to complete this process on the machine in minutes', null=True),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='net_time',
            field=models.IntegerField(blank=True, help_text='Net time required to complete this process in minutes', null=True),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='number_of_bindings',
            field=models.IntegerField(blank=True, help_text='Number of bindings required for this process', null=True),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='process',
            field=models.ForeignKey(blank=True, help_text='The manufacturing process this configuration belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.manufacturingprocess'),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='tool',
            field=models.ForeignKey(blank=True, help_text='Tool required for this process', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.tool'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['tool'], name='manufacturi_tool_id_c72881_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['control_gauge'], name='manufacturi_control_ce043c_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['fixture'], name='manufacturi_fixture_3f9f5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='processconfig',
            constraint=models.UniqueConstraint(fields=('workflow_process', 'machine_type'), name='unique_process_machine_config'),
        ),
    ]
