# Generated by Django 4.2.8 on 2025-06-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_update_process_config_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processconfig',
            name='process_con_machine_a0bd11_idx',
        ),
        migrations.RemoveIndex(
            model_name='processconfig',
            name='process_con_machine_339a41_idx',
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='machine_type',
        ),
    ]
