# Generated by Django 5.1.5 on 2025-02-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_alter_bomcomponent_options_and_more'),
        ('manufacturing', '0009_convert_manufacturing_year_to_date'),
    ]

    operations = [
    ]
