# Generated by Django 5.1.5 on 2025-03-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_alter_processconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processconfig',
            name='process',
        ),
    ]
