# Generated by Django 5.1.5 on 2025-03-15 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_controlgauge_stock_type'),
        ('manufacturing', '0011_remove_processconfig_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(help_text="Version number of the workflow (e.g., '1.0', '2.1')", max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current status of this workflow version', max_length=20)),
                ('effective_date', models.DateField(blank=True, help_text='Date when this workflow version becomes/became active', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this workflow version', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Workflow',
                'verbose_name_plural': 'Product Workflows',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workflowprocess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='process',
        ),
        migrations.RemoveField(
            model_name='workflowprocess',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subworkorderprocess',
            name='workflow_process',
        ),
        migrations.AlterModelOptions(
            name='processconfig',
            options={'ordering': ['workflow', 'sequence_order'], 'verbose_name': 'Process Configuration', 'verbose_name_plural': 'Process Configurations'},
        ),
        migrations.RemoveConstraint(
            model_name='processconfig',
            name='unique_process_machine_config',
        ),
        migrations.RemoveIndex(
            model_name='manufacturingprocess',
            name='manufacturi_machine_eb608f_idx',
        ),
        migrations.RemoveIndex(
            model_name='processconfig',
            name='manufacturi_workflo_15238b_idx',
        ),
        migrations.RemoveIndex(
            model_name='processconfig',
            name='manufacturi_axis_co_8941db_idx',
        ),
        migrations.RemoveIndex(
            model_name='subworkorderprocess',
            name='manufacturi_workflo_51cefd_idx',
        ),
        migrations.RemoveField(
            model_name='manufacturingprocess',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='processconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date when this configuration version becomes/became active', null=True),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='process',
            field=models.ForeignKey(help_text='The manufacturing process being configured', null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.manufacturingprocess'),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='sequence_order',
            field=models.IntegerField(default=1, help_text='Order in which this process should be executed'),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current status of this process configuration', max_length=20),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='stock_code',
            field=models.CharField(blank=True, help_text='Stock code for the process output', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='version',
            field=models.CharField(default='1.0', help_text="Version number of the process configuration (e.g., '1.0', '2.1')", max_length=20),
        ),
        migrations.AlterField(
            model_name='processconfig',
            name='number_of_bindings',
            field=models.IntegerField(default=1, help_text='Number of bindings/setups required for this process'),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='product',
            field=models.ForeignKey(help_text='Product this workflow belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='processconfig',
            name='workflow',
            field=models.ForeignKey(help_text='The workflow this process configuration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_configs', to='manufacturing.productworkflow'),
        ),
        migrations.AlterUniqueTogether(
            name='processconfig',
            unique_together={('workflow', 'process', 'version'), ('workflow', 'sequence_order', 'version')},
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['workflow', 'sequence_order'], name='manufacturi_workflo_933415_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['workflow', 'process'], name='manufacturi_workflo_6f06e6_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['status'], name='manufacturi_status_d20cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='processconfig',
            index=models.Index(fields=['version'], name='manufacturi_version_f2564a_idx'),
        ),
        migrations.AddIndex(
            model_name='productworkflow',
            index=models.Index(fields=['product', 'status'], name='manufacturi_product_4be076_idx'),
        ),
        migrations.AddIndex(
            model_name='productworkflow',
            index=models.Index(fields=['product', 'version'], name='manufacturi_product_1db6ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productworkflow',
            unique_together={('product', 'version')},
        ),
        migrations.RemoveField(
            model_name='processconfig',
            name='workflow_process',
        ),
        migrations.DeleteModel(
            name='WorkflowProcess',
        ),
    ]
