# Generated by Django 5.1.5 on 2025-02-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_alter_machine_internal_cooling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomprocessconfig',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='bomprocessconfig',
            name='axis_count',
            field=models.CharField(blank=True, choices=[('9EKSEN', '9 Eksen'), ('8.5EKSEN', '8.5 Eksen'), ('5EKSEN', '5 Eksen'), ('4EKSEN', '4 Eksen'), ('3EKSEN', '3 Eksen'), ('2EKSEN', '2 Eksen'), ('1EKSEN', '1 Eksen')], help_text='Required machine axis count for this process configuration', max_length=20, null=True),
        ),
    ]
