# Generated by Django 5.1.5 on 2025-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_productworkflow_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productworkflow',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='axis_count',
            field=models.CharField(blank=True, choices=[('9EKSEN', '9 Eksen'), ('8.5EKSEN', '8.5 Eksen'), ('5EKSEN', '5 Eksen'), ('4EKSEN', '4 Eksen'), ('3EKSEN', '3 Eksen'), ('2EKSEN', '2 Eksen'), ('1EKSEN', '1 Eksen'), ('NONE', 'NONE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processconfig',
            name='axis_count',
            field=models.CharField(blank=True, choices=[('9EKSEN', '9 Eksen'), ('8.5EKSEN', '8.5 Eksen'), ('5EKSEN', '5 Eksen'), ('4EKSEN', '4 Eksen'), ('3EKSEN', '3 Eksen'), ('2EKSEN', '2 Eksen'), ('1EKSEN', '1 Eksen'), ('NONE', 'NONE')], help_text='Type of machine axis required for this process', max_length=20, null=True),
        ),
    ]
