# Generated by Django 5.1.5 on 2025-02-19 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_technicaldrawing_drawing_url_and_more'),
        ('manufacturing', '0013_remove_bomcomponent_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomcomponent',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='process_config',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='bomcomponent',
            options={'ordering': ['sequence_order']},
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='standard_part',
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProcessComponent',
            fields=[
                ('bomcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.bomcomponent')),
                ('process_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.bomprocessconfig')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial')),
            ],
            options={
                'abstract': False,
            },
            bases=('manufacturing.bomcomponent',),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('bomcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manufacturing.bomcomponent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('manufacturing.bomcomponent',),
        ),
    ]
