# Generated by Django 5.1.5 on 2025-03-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_controlgauge_stock_type'),
        ('manufacturing', '0013_alter_productworkflow_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomcomponent',
            name='lead_time_days',
        ),
        migrations.AlterField(
            model_name='bom',
            name='parent_bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_boms', to='manufacturing.bom'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.product', to_field='product_code'),
        ),
    ]
