# Generated by Django 5.1.5 on 2025-02-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0014_remove_bomcomponent_raw_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderoutput',
            name='inspection_required',
            field=models.BooleanField(default=False, help_text='Whether quality inspection is required'),
        ),
        migrations.AddField(
            model_name='workorderoutput',
            name='quarantine_reason',
            field=models.TextField(blank=True, help_text='Reason for quarantine status if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='workorderoutput',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Good Quality'), ('REWORK', 'Needs Rework'), ('SCRAP', 'Scrap'), ('QUARANTINE', 'In Quarantine')], max_length=20),
        ),
    ]
