# Generated by Django 5.1.5 on 2025-02-20 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def migrate_bom_data(apps, schema_editor):
    BOM = apps.get_model('manufacturing', 'BOM')
    BOMNew = apps.get_model('manufacturing', 'BOMNew')
    Product = apps.get_model('inventory', 'Product')
    db_alias = schema_editor.connection.alias
    
    # Get all products with their codes
    products = {p.id: p.product_code for p in Product.objects.using(db_alias).all()}
    
    # Update all BOMs to use product codes
    for bom in BOM.objects.using(db_alias).all():
        if bom.product_id in products:
            # Create new BOM record with product_code
            BOMNew.objects.using(db_alias).create(
                product_id=products[bom.product_id],
                version=bom.version,
                is_active=bom.is_active,
                created_at=bom.created_at,
                modified_at=bom.modified_at,
                created_by=bom.created_by,
                modified_by=bom.modified_by
            )

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_technicaldrawing_drawing_url_and_more'),
        ('manufacturing', '0015_workorderoutput_inspection_required_and_more'),
    ]

    operations = [
        # Step 1: Create new BOM table with product_code as foreign key
        migrations.CreateModel(
            name='BOMNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey('inventory.Product', on_delete=django.db.models.deletion.PROTECT, to_field='product_code')),
                ('created_by', models.ForeignKey('erp_core.User', null=True, blank=True, on_delete=models.PROTECT, related_name='%(class)s_created')),
                ('modified_by', models.ForeignKey('erp_core.User', null=True, blank=True, on_delete=models.PROTECT, related_name='%(class)s_modified')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'unique_together': {('product', 'version')},
                'indexes': [models.Index(fields=['product'], name='bom_product_idx')],
            },
        ),
        
        # Step 2: Copy data from old table to new table
        migrations.RunPython(
            migrate_bom_data,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Step 3: Drop old table
        migrations.DeleteModel(
            name='BOM',
        ),
        
        # Step 4: Rename new table to old table name
        migrations.RenameModel(
            old_name='BOMNew',
            new_name='BOM',
        ),
    ]
