# Generated by Django 5.1.5 on 2025-03-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0015_alter_bom_product'),
        ('manufacturing', 'fix_bom_null_products'),
    ]

    operations = [
    ]
