# Generated by Django 5.1.5 on 2025-03-22 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_controlgauge_stock_type'),
        ('manufacturing', '0016_merge_0015_alter_bom_product_fix_bom_null_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='lead_time_days',
            field=models.IntegerField(blank=True, help_text='Expected lead time in days for this component', null=True),
        ),
        migrations.AlterField(
            model_name='bom',
            name='parent_bom',
            field=models.ForeignKey(blank=True, help_text='The BOM this version was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_boms', to='manufacturing.bom'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
