# Generated by Django 5.1.5 on 2025-02-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0016_alter_bom_product'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bom',
            new_name='manufacturi_product_60b29a_idx',
            old_name='bom_product_idx',
        ),
    ]
