# Generated by Django 5.1.5 on 2025-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0017_rename_bom_product_idx_manufacturi_product_60b29a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='component_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Component'), ('PROCESS', 'Process Component')], default='PRODUCT', max_length=20),
        ),
    ]
