# Generated by Django 5.1.5 on 2025-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0019_auto_20250224_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomcomponent',
            name='component_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Component'), ('PROCESS', 'Process Component')], default='PRODUCT', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='bomprocessconfig',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subworkorderprocess',
            name='planned_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
