# Generated by Django 5.1.5 on 2025-02-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0021_alter_subworkorderprocess_planned_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkorderprocess',
            name='planned_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
