# Generated by Django 5.1.5 on 2025-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0022_alter_subworkorderprocess_planned_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomcomponent',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
