# Generated by Django 5.1.5 on 2025-02-25 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_technicaldrawing_drawing_url_and_more'),
        ('manufacturing', '0025_auto_20250224_0649'),
        ('sales', '0004_shipping_actual_delivery_date_shipping_carrier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['is_active'], name='manufacturi_is_acti_40200b_idx'),
        ),
        migrations.AddIndex(
            model_name='bomcomponent',
            index=models.Index(fields=['bom'], name='manufacturi_bom_id_dc85e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bomcomponent',
            index=models.Index(fields=['component_type'], name='manufacturi_compone_7c1ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='bomprocessconfig',
            index=models.Index(fields=['process'], name='manufacturi_process_0f64af_idx'),
        ),
        migrations.AddIndex(
            model_name='bomprocessconfig',
            index=models.Index(fields=['axis_count'], name='manufacturi_axis_co_0c8f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='manufacturi_status_398ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['machine_type'], name='manufacturi_machine_43117d_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingprocess',
            index=models.Index(fields=['machine_type'], name='manufacturi_machine_eb608f_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['status'], name='manufacturi_status_389beb_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['parent_work_order'], name='manufacturi_parent__a7471b_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['sub_work_order'], name='manufacturi_sub_wor_5cbfb1_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['machine'], name='manufacturi_machine_6ab787_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='manufacturi_status_305de3_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='manufacturi_priorit_cd3830_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['status'], name='manufacturi_status_0153b9_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['sub_work_order'], name='manufacturi_sub_wor_9b110c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['target_category'], name='manufacturi_target__315ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['inspection_required'], name='manufacturi_inspect_72c913_idx'),
        ),
    ]
