# Generated by Django 5.1.5 on 2025-02-27 06:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_technicaldrawing_drawing_url_and_more'),
        ('manufacturing', '0026_bom_manufacturi_is_acti_40200b_idx_and_more'),
        ('sales', '0004_shipping_actual_delivery_date_shipping_carrier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], max_length=20)),
                ('to_status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bom',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bom',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='parent_bom',
            field=models.ForeignKey(blank=True, help_text='The BOM this version was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_boms', to='manufacturing.bom'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Indicates if this component is critical for the BOM'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='lead_time_days',
            field=models.IntegerField(blank=True, help_text='Expected lead time in days for this component', null=True),
        ),
        migrations.AddField(
            model_name='subworkorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sub_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subworkorder',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of work completed', max_digits=5),
        ),
        migrations.AddField(
            model_name='subworkorderprocess',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkorderprocess',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkorderprocess',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subworkorderprocess',
            name='setup_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkorderprocess',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkorderprocess',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SETUP', 'Machine Setup'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of work completed', max_digits=5),
        ),
        migrations.AddField(
            model_name='workorderoutput',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subworkorder',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subworkorder',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subworkorderprocess',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manufacturing.machine'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorderoutput',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['is_approved'], name='manufacturi_is_appr_93510b_idx'),
        ),
        migrations.AddIndex(
            model_name='bomcomponent',
            index=models.Index(fields=['is_critical'], name='manufacturi_is_crit_e918c9_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['planned_start'], name='manufacturi_planned_3030bc_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorder',
            index=models.Index(fields=['planned_end'], name='manufacturi_planned_b11565_idx'),
        ),
        migrations.AddIndex(
            model_name='subworkorderprocess',
            index=models.Index(fields=['status'], name='manufacturi_status_866069_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['planned_start'], name='manufacturi_planned_061555_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['planned_end'], name='manufacturi_planned_2c495e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderoutput',
            index=models.Index(fields=['production_date'], name='manufacturi_product_8fa06e_idx'),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderstatuschange',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='manufacturing.workorder'),
        ),
        migrations.AddIndex(
            model_name='workorderstatuschange',
            index=models.Index(fields=['work_order'], name='manufacturi_work_or_5b924c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderstatuschange',
            index=models.Index(fields=['changed_at'], name='manufacturi_changed_b920fc_idx'),
        ),
    ]
