# Generated by Django 5.1.5 on 2025-02-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_technicaldrawing_drawing_url_and_more'),
        ('manufacturing', '0027_workorderstatuschange_bom_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomprocessconfig',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial'),
        ),
    ]
