# Generated by Django 5.1.5 on 2025-02-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_processproduct'),
        ('manufacturing', '0028_bomprocessconfig_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomprocessconfig',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use process_products instead', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
