# Generated by Django 5.1.5 on 2025-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_processproduct_bom_process_configs'),
        ('manufacturing', '0029_bomprocessconfig_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomprocessconfig',
            name='process_products',
            field=models.ManyToManyField(blank=True, help_text='Process products associated with this configuration', related_name='process_configs', to='inventory.processproduct'),
        ),
    ]
