# Generated by Django 5.1.5 on 2025-02-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0031_remove_bomprocessconfig_process_products_and_more'),
        ('manufacturing', 'new_migration'),
    ]

    operations = [
    ]
