# Generated by Django 5.1.5 on 2025-02-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_processproduct_bom_process_configs'),
        ('manufacturing', '0032_merge_20250228_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomprocessconfig',
            name='process_product',
            field=models.OneToOneField(blank=True, help_text='Process product associated with this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_process_config', to='inventory.processproduct'),
        ),
    ]
