# Generated by Django 5.1.5 on 2025-02-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_processproduct_bom_process_configs'),
        ('manufacturing', '0035_remove_bomprocessconfig_process_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomprocessconfig',
            name='process_product',
        ),
        migrations.AddField(
            model_name='bomprocessconfig',
            name='process_product',
            field=models.ForeignKey(blank=True, help_text='Process product associated with this configuration', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_process_configs', to='inventory.processproduct'),
        ),
    ]
