# Generated by Django 4.2.8 on 2025-05-24 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_code_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0002_alter_goodsreceipt_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('lead_time_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'supplier_product_info',
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionitem',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.DeleteModel(
            name='SupplierPriceList',
        ),
        migrations.AddField(
            model_name='supplierproductinfo',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='purchasing.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproductinfo',
            unique_together={('supplier', 'product')},
        ),
    ]
