# Generated by Django 4.2.8 on 2025-06-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_code_fields'),
        ('maintenance', '0002_alter_calibrationrecord_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calibrationrecord',
            name='calibration_control_bd1694_idx',
        ),
        migrations.RemoveIndex(
            model_name='calibrationrecord',
            name='calibration_status_f95eeb_idx',
        ),
        migrations.RemoveIndex(
            model_name='calibrationrecord',
            name='calibration_certifi_cef4b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='fixturecheck',
            name='fixture_che_fixture_6bd9ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='fixturecheck',
            name='fixture_che_status_073dad_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancelog',
            name='maintenance_equipme_6f7a82_idx',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='work_center',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_usage', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['calibration_date'], name='calibration_calibra_fc7675_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationrecord',
            index=models.Index(fields=['control_gauge'], name='calibration_control_509aae_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturecheck',
            index=models.Index(fields=['check_date'], name='fixture_che_check_d_59c4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='fixturecheck',
            index=models.Index(fields=['fixture'], name='fixture_che_fixture_3670af_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['maintenance_date'], name='maintenance_mainten_ed2b27_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['equipment'], name='maintenance_equipme_bf45a0_idx'),
        ),
    ]
