# Generated by Django 5.1.5 on 2025-02-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0003_customer_created_at_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-employee_id']},
        ),
    ]
