# Generated by Django 5.1.5 on 2025-01-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-order_date']},
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
    ]
