# Generated by Django 5.1.5 on 2025-03-06 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0004_alter_userprofile_options'),
        ('inventory', '0002_alter_product_product_type_holder_tool'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField()),
                ('package_number', models.PositiveIntegerField(default=1)),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_numbers', models.JSONField(blank=True, default=list, help_text='List of serial numbers for tracked items')),
            ],
            options={
                'ordering': ['package_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='shipping',
            name='handling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='priority',
            field=models.CharField(choices=[('STANDARD', 'Standard Shipping'), ('EXPRESS', 'Express Shipping'), ('PRIORITY', 'Priority Shipping'), ('SAME_DAY', 'Same Day Delivery')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='shipping',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='recipient_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shipping',
            name='recipient_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shipping',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='total_packages',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_address_line1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed Delivery'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='sales_sales_order_n_78c57a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'order_date'], name='sales_sales_status_fc0419_idx'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.shipping'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'order_item', 'package_number')},
        ),
    ]
