# Generated by Django 5.1.5 on 2025-03-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_shipmentitem_shipping_handling_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='kapsam_deadline_date',
            field=models.DateField(blank=True, help_text='Deadline date for kapsam', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_receiving_date',
            field=models.DateField(blank=True, help_text='Date when the order was received from customer', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
