# Generated by Django 4.2.8 on 2025-05-24 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_supplierproductinfo_remove_purchaseorder_currency_and_more'),
        ('sales', '0002_alter_customerpricelist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerpricelist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customerpricelist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerpricelist',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customerpricelist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerpricelist',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='customerpricelist',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesorderitem',
            options={'ordering': ['order_date', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_order_custome_17b089_idx',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='salesquotation',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesquotationitem',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='salesquotationitem',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salesquotationitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='kapsam_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='sales_order_custome_21b704_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['order_date'], name='sales_order_order_d_e43f14_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['delivery_date'], name='sales_order_deliver_20faa1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['kapsam_deadline_date'], name='sales_order_kapsam__6be330_idx'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='CustomerPriceList',
        ),
    ]
