# Generated by Django 4.2.8 on 2025-05-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customerpricelist_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_order_status_1f3c2e_idx',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='status',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PRODUCTION', 'In Production'), ('READY', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['status'], name='sales_order_status_10449a_idx'),
        ),
    ]
