# Generated by Django 5.1.5 on 2025-02-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='carrier_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='insurance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='package_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='package_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='package_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed Delivery'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='shipping',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
