# Generated by Django 5.1.5 on 2025-03-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_shipping_actual_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='package_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shipping',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='shipping',
            unique_together={('order', 'order_item', 'package_number')},
        ),
        migrations.DeleteModel(
            name='ShipmentItem',
        ),
    ]
