# Generated by Django 4.2.8 on 2025-05-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_move_status_to_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipping_no', models.CharField(max_length=50)),
                ('shipping_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('package_number', models.PositiveIntegerField(default=1)),
                ('shipping_note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.salesorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.salesorderitem')),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shippings',
                'db_table': 'sales_shipments',
                'ordering': ['-shipping_date'],
                'indexes': [models.Index(fields=['shipping_no'], name='sales_shipm_shippin_bd43fe_idx'), models.Index(fields=['shipping_date'], name='sales_shipm_shippin_a984cc_idx'), models.Index(fields=['order'], name='sales_shipm_order_i_6f1ad3_idx'), models.Index(fields=['order_item'], name='sales_shipm_order_i_3b8b90_idx')],
                'unique_together': {('shipping_no', 'order', 'order_item')},
            },
        ),
    ]
