# Generated by Django 5.1.5 on 2025-03-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_shipping_order_item_shipping_package_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
