# Generated by Django 5.1.5 on 2025-03-06 18:40

from django.db import migrations

def handle_null_values(apps, schema_editor):
    Shipping = apps.get_model('sales', 'Shipping')
    # Delete any shipping records with NULL values since they are invalid
    Shipping.objects.filter(order_item__isnull=True).delete()
    Shipping.objects.filter(quantity__isnull=True).delete()

def reverse_handle_null_values(apps, schema_editor):
    pass  # No reverse operation needed

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_shipping_order_item_alter_shipping_quantity'),
    ]

    operations = [
        migrations.RunPython(handle_null_values, reverse_handle_null_values),
    ]
