# Generated by Django 5.1.5 on 2025-03-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_handle_null_shipping_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_amount',
        ),
    ]
