# Generated by Django 5.1.5 on 2025-03-08 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0004_alter_userprofile_options'),
        ('sales', '0009_alter_shipping_order_alter_shipping_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_sales_status_fc0419_idx',
        ),
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='kapsam_deadline_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='order_receiving_date',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Deadline date for the order item', null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='kapsam_deadline_date',
            field=models.DateField(blank=True, help_text='Deadline date for kapsam for the order item', null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='receiving_date',
            field=models.DateField(blank=True, help_text='Date when the order item was received from customer', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'created_at'], name='sales_sales_status_a6eb5c_idx'),
        ),
    ]
