# Generated by Django 5.1.5 on 2025-03-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipping',
            unique_together=set(),
        ),
    ]
