# Generated by Django 5.1.5 on 2025-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_shipping_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='shipping',
            unique_together={('shipping_no', 'order')},
        ),
    ]
