# Generated by Django 5.1.5 on 2025-03-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_shipping_shipping_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipping',
            unique_together={('shipping_no', 'order', 'order_item')},
        ),
    ]
