# Generated by Django 5.1.5 on 2025-04-16 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_update_shipping_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
